name: CI Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Build grpc-spring
        run: mvn clean install
        working-directory: ./grpc-spring

      - name: Build pattern-design
        run: mvn clean install
        working-directory: ./pattern-design

      - name: Build rocketmq
        run: mvn clean install
        working-directory: ./rocketmq